### ISSUE TITLE
EMF 3.3.2 compatibility issue on 1.21.11 - NoSuchMethodError in EMF integration

### ISSUE THREAD

**Issue by Adriano2056** [dbrighthd/elytratrails#31]
# EMF 3.3.2 compatibility issue on Minecraft 1.21.11 - NoSuchMethodError in EMF integration

Hi! I found a compatibility issue between Elytra Contrails 1.4.8.7 for Minecraft 1.21.11 and newer versions of Entity Model Features (EMF) / Entity Texture Features (ETF).

I investigated the crash, modified the 1.21.11 source code, updated the EMF integration, and was able to successfully compile the mod and launch Minecraft with the updated version.

## Environment

- Minecraft: 1.21.11
- Mod Loader: Fabric
- Elytra Contrails: 1.4.8.7-1.21.11
- Entity Model Features (EMF): 3.3.2
- Entity Texture Features (ETF): 7.2

Original 1.21.11 source branch:
https://github.com/dbrighthd/elytratrails/tree/1.21.11

## Problem

The current Elytra Contrails 1.21.11 branch is built against older versions of EMF and ETF.

The current `gradle.properties` uses:

```properties
emf_version=3.0.11-fabric-1.21.11
etf_version=7.0.9-fabric-1.21.11
```

When using Elytra Contrails 1.4.8.7 together with EMF 3.3.2, Minecraft crashes because the Elytra Contrails EMF compatibility implementation calls methods from an older EMF API.

The original runtime error was:

```text
java.lang.NoSuchMethodError:
'traben.entity_model_features.models.animation.state.EMFEntityRenderState traben.entity_model_features.models.animation.EMFAnimationEntityContext.getEmfState()'
```

The stack trace points directly to the Elytra Contrails EMF integration:

```text
traben.entity_model_features.models.parts.EMFModelPartRoot.handler$clk000$elytratrails$onEmfRootRegistered
```

This means Elytra Contrails is trying to call an EMF method/signature that is no longer available in the installed EMF 3.3.2 version.

## Investigation

I downloaded the Elytra Contrails `1.21.11` source and changed the development dependencies to compile against:

```text
EMF 3.3.2
ETF 7.2
```

After doing this, Java compilation exposed additional usages of the old EMF API.

The relevant obsolete calls included:

```java
EMFAnimationEntityContext.getEmfState()
```

and:

```java
EMFAnimationEntityContext.setCurrentEntityNoIteration(state);

emfRoot.triggerManualAnimation(new PoseStack());

EMFAnimationEntityContext.setCurrentEntityNoIteration(null);
```

These methods/calls are no longer available in the same form when compiling against EMF 3.3.2.

## Changes / Fix

For the render-state access responsible for the original `NoSuchMethodError`, the old access through:

```java
EMFAnimationEntityContext.getEmfState()
```

was replaced with the current EMF state access:

```java
var state = EMFState.state();

if (state == null) {
    return;
}
```

This avoids calling the removed/incompatible `getEmfState()` method.

The old manual animation sequence:

```java
EMFAnimationEntityContext.setCurrentEntityNoIteration(state);

emfRoot.triggerManualAnimation(new PoseStack());

EMFAnimationEntityContext.setCurrentEntityNoIteration(null);
```

was also incompatible with EMF 3.3.2.

It was replaced with the current public EMF animation API:

```java
EMFAnimationApi.animateModelForEntity(emfEntity, emfRoot, false);
```

This allows EMF itself to handle the required animation/render state instead of Elytra Contrails manually manipulating the old animation context.

The development dependencies were also updated from:

```properties
emf_version=3.0.11-fabric-1.21.11
etf_version=7.0.9-fabric-1.21.11
```

to the corresponding EMF 3.3.2 / ETF 7.2 versions for Minecraft 1.21.11.

## Compilation

After updating the compatibility implementation, I ran:

```bash
gradlew clean build
```

The modified Elytra Contrails 1.21.11 source successfully compiled against EMF 3.3.2 / ETF 7.2.

The original source produced compilation errors related to the removed EMF API methods, while the modified implementation compiled successfully.

## Current Test Result

The resulting jar was installed into Minecraft 1.21.11 together with:

```text
Elytra Contrails 1.4.8.7-1.21.11
EMF 3.3.2
ETF 7.2
```

Minecraft successfully launched with the modified build.

The original `NoSuchMethodError` that prevented the game from working with EMF 3.3.2 no longer occurs during startup.

Further in-game testing while flying with an Elytra and using EMF-based models/resource packs would still be useful to verify every part of the integration.

## Summary

It looks like the Minecraft 1.21.11 branch does not require a major rewrite.

The main problem is that its EMF compatibility layer was compiled against the older EMF 3.0.x API.

Updating the EMF/ETF dependencies and migrating the old EMF context/manual-animation calls to the current EMF API allows the project to compile against EMF 3.3.2 and launch Minecraft successfully.

I can provide the modified source code / diff if needed.

---------------------------------------------------------------------------

## Update: In-game testing successful

I have now tested the modified build in actual gameplay.

### Test environment

- Minecraft: 1.21.11
- Fabric
- Elytra Contrails: modified 1.21.11 build
- EMF: 3.3.2
- ETF: 7.2

### Result

The game successfully launches, loads into a world, and is playable.

I also tested the mod during normal gameplay and so far I have not encountered the original `NoSuchMethodError` or another crash related to the EMF integration.

So far the compatibility changes appear to be working correctly in-game with EMF 3.3.2 + ETF 7.2.

The changes that resolved the compatibility issue were mainly:

```java
EMFAnimationEntityContext.getEmfState()
```

being migrated to the current state API:

```java
var state = EMFState.state();
if (state == null) return;
```

and the old manual animation flow:

```java
EMFAnimationEntityContext.setCurrentEntityNoIteration(state);
emfRoot.triggerManualAnimation(new PoseStack());
EMFAnimationEntityContext.setCurrentEntityNoIteration(null);
```

being replaced with the current public EMF animation API:

```java
EMFAnimationApi.animateModelForEntity(emfEntity, emfRoot, false);
```

At this point the modified 1.21.11 build:

- compiles successfully against EMF 3.3.2 / ETF 7.2;
- launches Minecraft successfully;
- loads into a world successfully;
- is playable during actual gameplay;
- no longer produces the original EMF `NoSuchMethodError`.

I will continue testing, but so far the fix appears to be working correctly.

**Comment by dbrighthd** [comment]
Hello, I will be updating Elytra Contrails soon with support for newer EMF versions

My and traben's fix is already on the 26.2 branch and will be back-ported to the 1.21.11 and 26.1 versions after I update 26.2 on modrinth.

Thank you for the investigative effort!

**Comment by Adriano2056** [comment]
Thank you for the response and for the clarification!

During our investigation, we actually noticed that the 26.2 branch had already been migrated to the newer EMF API. We compared the 1.21.11 implementation with the 26.2 branch and used that newer implementation as one of the main references for understanding what had changed in EMF and how the 1.21.11 compatibility code needed to be updated.

In particular, seeing the newer EMF state handling in the 26.2 branch helped confirm that the old EMFAnimationEntityContext approach used by the 1.21.11 version was outdated.

The fix is already included in the modified 1.21.11 source/build that we mentioned and tested. We updated the old EMF calls to the newer API, including the state handling and manual animation path, and the resulting build successfully compiles and is working in-game with EMF 3.3.2 + ETF 7.2.

So it's great to know that the official fix from you and Traben is already implemented on 26.2 and that you plan to back-port it to 1.21.11.

Thank you both for maintaining the compatibility and for taking the time to respond! And thank you for confirming our findings. I'll switch back to the official 1.21.11 build as soon as the back-port is released.

[elytratrails-1.21.11.zip](https://github.com/user-attachments/files/31719676/elytratrails-1.21.11.zip)

**Comment by dbrighthd** [comment]
Fixed, use latest for 1.21.11 on modrinth!
